// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlmK3RsIDI8NPwjerHW46KSIC-izAPtI',
    appId: '1:291660774638:web:b1a8edd9d8b458360307ff',
    messagingSenderId: '291660774638',
    projectId: 'first-firebase-project-9f10d',
    authDomain: 'first-firebase-project-9f10d.firebaseapp.com',
    storageBucket: 'first-firebase-project-9f10d.firebasestorage.app',
    measurementId: 'G-6WNVS8J4LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4tuhxLEPOnxozEKlGK6s1F7tRkfXi-jI',
    appId: '1:291660774638:android:d9120b766fe525780307ff',
    messagingSenderId: '291660774638',
    projectId: 'first-firebase-project-9f10d',
    storageBucket: 'first-firebase-project-9f10d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Sq61ysoVP87JJ6hKHpTsWuelGgPrWds',
    appId: '1:291660774638:ios:87ec7035415603600307ff',
    messagingSenderId: '291660774638',
    projectId: 'first-firebase-project-9f10d',
    storageBucket: 'first-firebase-project-9f10d.firebasestorage.app',
    iosBundleId: 'com.example.preschoolLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Sq61ysoVP87JJ6hKHpTsWuelGgPrWds',
    appId: '1:291660774638:ios:87ec7035415603600307ff',
    messagingSenderId: '291660774638',
    projectId: 'first-firebase-project-9f10d',
    storageBucket: 'first-firebase-project-9f10d.firebasestorage.app',
    iosBundleId: 'com.example.preschoolLearningApp',
  );
}
